# Adapted from https://github.com/HumanBrainProject/openMINDS/blob/871e382/.github/workflows/validate-schemas.yml
# MIT licensed

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: openMINDS

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3
  workflow_dispatch:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule sync
        git submodule update --init --recursive --remote
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout generator repo
      uses: actions/checkout@v2
      with:
        repository: HumanBrainProject/openMINDS_generator
        ref: generator_update #To be changed back to main as soon as the branch is merged
        path: generator
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f generator/requirements.txt ]; then pip install -r generator/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run generation
      run: |
        python generator/openMINDS.py
        python vocab/vocab_extractor.py
    - name: Checkout documentation branch
      uses: actions/checkout@v2
      with:
        repository: HumanBrainProject/openMINDS
        ref: documentation
        path: documentation
    - name: Push documentation
      run: |
        cp -r target/html/* documentation
        cp -r target/uml/* documentation
        cp -r target/schema.json/* documentation
        cd documentation
        git config user.name openMINDS
        git config user.email openMINDS@ebrains.eu
        if [[ $(git add . --dry-run | wc -l) -gt 0 ]]; then
            git add .
            git commit -m "Update of documentation"
            git push
        else
            echo "Nothing to commit"
        fi
        cd ..
        rm -rf documentation
    - name: Archive expanded version
      uses: actions/upload-artifact@v2
      with:
        name: expanded schema templates
        path: |
          expanded
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: target files
        path: |
          target
    - run: |
        git config user.name openMINDS
        git config user.email openMINDS@ebrains.eu
        if [[ $(git add . --dry-run | wc -l) -gt 0 ]]; then
            git add .
            git commit -m "Automated vocabulary extraction"
            git push
        else
            echo "Nothing to commit"
        fi
